### ISSUE TITLE
little proposal

### ISSUE THREAD

**Issue by iridescentGray** [JuanMaDev98/my-bank#1]
you looks like  commit some shouldn't commit file to github，such as  '.idea'  '.vscode' and '__pycache__' .

Solution is add the following  lines  into your '.gitignore' file :
/.idea
/.vscode
__pycache__

then You will won't make this mistakes again.

**Comment by JuanMaDev98** [comment]
I was beign lazy on this, thanks for openning this issue, it gave me the strength to do this right, its done now
